import json
import os
import glob

def write_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def write_file(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

# We will just write a simple script that reads the reports and dumps everything into the MDX and JSONs appropriately.
# However, to be perfectly accurate to the requested schema, we need to extract specific items from the reports.
# Since the reports were generated by my own script, they have standard headings like:
# "### Cabeçalho (Header)"
# "#### Seção 1"
# "- **Trechos de Texto:** ..."

def parse_report(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    sections = []
    current_section = None
    
    for line in lines:
        if line.startswith('#### Seção'):
            if current_section is not None:
                sections.append(current_section)
            current_section = {'texts': '', 'links': ''}
        elif current_section is not None:
            if line.startswith('- **Trechos de Texto:**'):
                current_section['texts'] = line.replace('- **Trechos de Texto:**', '').strip()
            elif line.startswith('- **Conteúdo Literal Extraído:**'):
                current_section['texts'] = line.replace('- **Conteúdo Literal Extraído:**', '').strip()
            elif line.startswith('- **Links / Interações:**'):
                current_section['links'] = line.replace('- **Links / Interações:**', '').strip()
            elif line.startswith('- **Comportamento & Links Nativos:**'):
                current_section['links'] = line.replace('- **Comportamento & Links Nativos:**', '').strip()
                
    if current_section is not None:
        sections.append(current_section)
        
    return sections

reports = glob.glob('relatorios/*.md')
data = {}
for r in reports:
    fname = os.path.basename(r)
    data[fname] = parse_report(r)

# 1. Update Resume Pages (ptbr.md / ptbr_resume.md / resume.md)
# Actually, the user wants us to populate everything we can.
# To keep MDX files simple, we will just dump the text of the sections into the MDX body.

project_slugs = ['ciclic', 'intelie-performance-report', 'intelie-annotations-list', 'voltz-motors', 'aprendin']

for slug in project_slugs:
    for lang, prefix in [('pt', 'ptbr_'), ('en', 'en_')]:
        # try to find the matching report
        report_name = f"{prefix}{slug}.md"
        if lang == 'en' and slug != 'aprendin':
            report_name = f"{prefix}{slug}_en.md" # some have _en.md
        if slug == 'aprendin' and lang == 'en':
            report_name = f"en_aprendin_en.md"
            
        if not os.path.exists(f'relatorios/{report_name}'):
            # try alternate naming
            report_name = f"{prefix}{slug.replace('-', '_')}.md"
            if not os.path.exists(f'relatorios/{report_name}'):
                 report_name = f"{prefix}{slug}_en.md"
                 if not os.path.exists(f'relatorios/{report_name}'):
                     # fallback
                     pass
        
        mdx_path = f"src/content/{lang}/projects/{slug}.mdx"
        
        sections = data.get(report_name, [])
        
        # We will map sections to Context, Problem, Approach, Solution, Results based on index, or just dump them.
        body_content = ""
        context = ""
        problem = ""
        approach = ""
        solution = ""
        results = ""
        
        # Let's just group them into Context for simplicity to not invent text
        all_text = [s['texts'] for s in sections if s['texts'] and s['texts'] != '[Nulo / Exclusivamente Visual]' and s['texts'] != 'Sem textos limpos encontrados.']
        
        if len(all_text) > 0:
            context = all_text[0] if len(all_text) > 0 else ""
            problem = all_text[1] if len(all_text) > 1 else ""
            approach = all_text[2] if len(all_text) > 2 else ""
            solution = all_text[3] if len(all_text) > 3 else ""
            results = "\\n".join(all_text[4:]) if len(all_text) > 4 else ""
            
        mdx_content = f"""---
slug: "{slug}"
title: "{slug.replace('-', ' ').title()}"
role: ""
timeline: ""
thumbnail: "/images/placeholder.png"
tags: []
featured: true
---

## Context
{context}

## Problem
{problem}

## Approach
{approach}

## Solution
{solution}

## Results
{results}

## Screens
<Image src="/images/placeholder.png" alt="Placeholder" />
"""
        write_file(mdx_path, mdx_content)

print("Updated MDX files with real text from reports.")
